"""empty message

Revision ID: 441c471c020d
Revises: d3776612cd07
Create Date: 2023-04-23 14:37:40.442297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441c471c020d'
down_revision = 'd3776612cd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'id')
    # ### end Alembic commands ###
