"""empty message

Revision ID: 162a5d671f7c
Revises: 441c471c020d
Create Date: 2023-04-23 14:40:01.119744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162a5d671f7c'
down_revision = '441c471c020d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('tickets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'concert_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'concert_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
