"""empty message

Revision ID: 56698b92e170
Revises: aec6bb78719c
Create Date: 2023-04-23 12:56:32.308696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56698b92e170'
down_revision = 'aec6bb78719c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'concert_id'),
    tickets_purchased=Column(None, Integer(), table=None, nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
