"""empty message

Revision ID: aec6bb78719c
Revises: dd86e0cca1c5
Create Date: 2023-04-23 12:53:34.379782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec6bb78719c'
down_revision = 'dd86e0cca1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venues_city_key', 'venues', type_='unique')
    op.drop_constraint('venues_state_key', 'venues', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('venues_state_key', 'venues', ['state'])
    op.create_unique_constraint('venues_city_key', 'venues', ['city'])
    # ### end Alembic commands ###
