"""empty message

Revision ID: d3776612cd07
Revises: 56698b92e170
Create Date: 2023-04-23 13:00:04.192582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3776612cd07'
down_revision = '56698b92e170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('tickets_purchased', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'concert_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
