"""empty message

Revision ID: 566a11cdc2f0
Revises: 88b72134e16e
Create Date: 2023-04-23 12:35:18.198525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566a11cdc2f0'
down_revision = '88b72134e16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues')
    # ### end Alembic commands ###
